PROCESSOR 16f877
INCLUDE <p16f877.inc>

ORG 0
GOTO INICIO
ORG 5

INICIO: 
		MOVLW H'FF'
		MOVWF H'40'
		MOVLW H'20'	;W = 20
		MOVWF FSR	;FSR = W
		MOVF INDF,0	;W = Primer elemento
LOOP:
		BTFSC FSR, 6
		GOTO $ 
		MOVF H'40', 0	
		SUBWF INDF, 0	;W = INDF - W
		BTFSS STATUS, C	;If (C == 1) Salta
		GOTO NEGATIVO
		GOTO POSITIVO
NEGATIVO:
		MOVF INDF, 0
		MOVWF H'40'
		INCF FSR,1	;FSR = FSR + 1
		GOTO LOOP
POSITIVO:
		INCF FSR, 1	;FSR = FSR + 1
		GOTO LOOP
		END