PROCESSOR 16F877A
INCLUDE<P16F877A.INC>

;DECLARACION DE CONSTANTES
C1 EQU 10H      ;C1 CON VALOR DE 10H
C2 EQU 50H      ;C2 CON VALOR DE 50H
C3 EQU 60H      ;C3 CON VALOR DE 60H

;DECLARACION DE VARIABLES
V1 EQU H'21'    ;ASIGNACION DE V1 EN 21H
V2 EQU H'22'    ;'''''''
V3 EQU H'23'   
V4 EQU H'24'  
V5 EQU H'25'   
V6 EQU H'26'   
V7 EQU H'27'   
V8 EQU H'28'   
V9 EQU H'00'   
V10 EQU H'01'        
V11 EQU H'02'   
V12 EQU H'03'   
V13 EQU H'04'   

ORG 0       
GOTO INICIO 
ORG 5       
  
INICIO:
	CLRF PORTA        
	CLRF PORTB        ;LIMPIEZA DE LOS PUERTOS A Y B
	BSF STATUS,RP0    ;CAMBIO AL BANCO DE RAM 1
	BCF STATUS,RP1
	MOVWF TRISB       
	CLRF PORTB        
	MOVLW H'06'      
	MOVWF ADCON1      ;PUERTO A CONFIGURADA COMO ENTRADA VIRTUAL
	MOVLW H'3F'       
	MOVWF TRISA       
	BCF STATUS,RP0    ;CAMBIO AL BANCO 0 DE RAM
	
CICLO:
	MOVLW V9          
	MOVWF V4          
	MOVFW PORTA        
	XORWF V4, W       
	BTFSC STATUS,Z     ;¿Z = 0?
	GOTO DETENER         ;DIRECCIONAR A DETENER
	
	MOVLW V10          
	MOVWF V5          
	MOVFW PORTA        
	XORWF V5, W       
	BTFSC STATUS,Z     ;¿Z = 0?
	GOTO GA180   ;DIRECCIONAR A GA180
	 
	MOVLW V11          
	MOVWF V6          
	MOVFW PORTA        
	XORWF V6, W       
	BTFSC STATUS,Z     ;¿Z = 0?
	GOTO GH180    ;DIRECCIONA A GH180
	
	MOVLW V12          
	MOVWF V7          
	MOVFW PORTA        
	XORWF V7, W       
	BTFSC STATUS,Z     ;¿Z = 0?
	GOTO GA90    ;DIRECCIONAR A GA90
	
	MOVLW V13         
	MOVWF V8          
	MOVFW PORTA        
	XORWF V8, W       
	BTFSC STATUS,Z     ;¿Z = 0?
	GOTO GH90     ;DIRECCIONAR A GH90
	
DETENER:
	MOVLW 0           
	MOVWF PORTB       
	GOTO CICLO        
	
GA180:
	MOVLW B'000101'   
	MOVWF PORTB       
	CALL RETARDO      
	GOTO CICLO        
	
GH180:
	MOVLW B'001010'   
	MOVWF PORTB       
	CALL RETARDO      
	GOTO CICLO       
	
GA90:
	MOVLW B'110011'   
	MOVWF PORTB       
	CALL RETARDO      
	GOTO CICLO        
	
GH90:
	MOVLW B'001100'  
	MOVWF PORTB       
	CALL RETARDO      
	GOTO CICLO        
	
RETARDO:
	MOVLW C1   
	MOVWF V1   
TRES:
	MOVWF C2   
	MOVWF V2   	  
DOS:
	MOVWF C3   
	MOVWF V3   
UNO:
	DECFSZ V3  
	GOTO UNO   
	DECFSZ V2  
	GOTO DOS   
	DECFSZ V1  
	GOTO TRES  
	RETURN     
	END        ;FIN DEL PROGRAMA